import assert from "node:assert/strict";
import { build } from "esbuild";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";

const root = fileURLToPath(new URL("../../../", import.meta.url));
const bundle = await build({ absWorkingDir: root, stdin: { contents: 'export * from "./apps/web/src/components/MetricComparisonTable"; export { PcaContribution } from "./apps/web/src/components/SopComparison"; export { InternalValidationCalculationDetails } from "./apps/web/src/components/InternalValidationCalculationDetails";', resolveDir: root },
  bundle: true, write: false, platform: "node", format: "cjs", packages: "external", jsx: "automatic", loader: { ".css": "empty" } });
const module = { exports: {} };
vm.runInThisContext(`(function(require,module,exports){${bundle.outputFiles[0].text}\n})`)(createRequire(import.meta.url), module, module.exports);
const { MetricComparisonTable, formatImprovement, formatMetric, PcaContribution, InternalValidationCalculationDetails } = module.exports;
const render = (component, props) => renderToStaticMarkup(React.createElement(component, props));
const values = { silhouette: 0.329681, davies_bouldin: 1.238391, calinski_harabasz: 1123.992 };
const changes = { silhouette: 12.42, davies_bouldin: -12.09, calinski_harabasz: 24.82 };
assert.equal(formatMetric(values.calinski_harabasz), "1,123.992000");
assert.equal(formatImprovement(12.424, "higher"), "+12.42%");
assert.equal(formatImprovement(-12.09, "lower"), "-12.09%");
assert.equal(formatImprovement(12.09, "lower", "direction-aware"), "-12.09%");
assert.equal(formatImprovement(-12.09, "lower", "direction-aware"), "+12.09%");
assert.equal(formatImprovement(-0, "lower", "direction-aware"), "0.00%");
assert.equal(formatImprovement(null, "lower"), "Unavailable");
assert.equal(formatImprovement(undefined, "higher"), "Unavailable");
const signed = render(MetricComparisonTable, { existing: values, enhanced: values, relativeChange: changes });
const directional = render(MetricComparisonTable, { existing: values, enhanced: values, relativeChange: { ...changes, davies_bouldin: 12.09 }, changeConvention: "direction-aware" });
assert.equal(signed, directional, "Both API conventions render identical signed changes");
assert.equal((signed.match(/scope="row"/g) ?? []).length, 3);
assert.match(signed, /0\.329681/); assert.match(signed, /1,123\.992000/);
assert.match(signed, /\+12\.42%<span[^>]*> ↑/); assert.match(signed, /-12\.09%<span[^>]*> ↓/);
assert.match(signed, /\+24\.82%<span[^>]*> ↑/);
assert.equal((signed.match(/internal-validation-enhanced font-semibold/g) ?? []).length, 6);
assert.match(signed, />Standard<\/th>/); assert.match(signed, />Enhanced<\/th>/); assert.match(signed, />Improvement<\/th>/);
const adverse = render(MetricComparisonTable, { relativeChange: { silhouette: -2, davies_bouldin: 2, calinski_harabasz: -2 } });
assert.equal((adverse.match(/internal-validation-enhanced font-semibold/g) ?? []).length, 3, "Only Enhanced metric cells are emphasized for adverse changes");
const pca = render(PcaContribution, { dimensions: 13, components: 6, existing: values, enhanced: values, relativeChange: changes, note: "Controlled random starts" });
assert.equal((pca.match(/scope="row"/g) ?? []).length, 1);
assert.doesNotMatch(pca, /Davies|Calinski/);
assert.match(pca, /View Calculation Details/); assert.match(pca, /<details/);
assert.match(pca, /Controlled random starts/);
const details = render(InternalValidationCalculationDetails, { standard: { n: 100, k: 2, metrics: values }, enhanced: { n: 100, k: 2, metrics: values } });
assert.match(details, /<details/); assert.match(details, /View Calculation Details/);
const standardOnly = render(MetricComparisonTable, { existing: values, standardOnly: true });
assert.doesNotMatch(standardOnly, />Enhanced<|>Improvement</);
console.log("PASS shared table rows, signed/direction-aware percentages, arrows, favorable styling, six/two-decimal formatting, PCA-only row and calculation disclosures");
